# Generated by Django 5.2.6 on 2025-09-12 21:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bustop',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('highway', models.CharField(blank=True, max_length=63, null=True)),
                ('way', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
            options={
                'db_table': 'planet_osm_point',
                'managed': False,
            },
        ),
    ]
